name: Daily Login

on:
  schedule:
    - cron: '0 0 * * *'  # 每天 UTC 时间 00:00 触发

jobs:
  login:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install selenium
          # 安装 Chrome 浏览器和 chromedriver
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable
          wget -q -O /tmp/chromedriver.zip https://chromedriver.storage.googleapis.com/$(wget -q -O - https://chromedriver.storage.googleapis.com/LATEST_RELEASE)/chromedriver_linux64.zip
          unzip /tmp/chromedriver.zip -d /usr/local/bin/

      - name: Run login script
        env:
          USERNAME: ${{ secrets.USERNAME }}
          PASSWORD: ${{ secrets.PASSWORD }}
        run: python login_script.py
